services:
  db:
    image: postgres:15-alpine
    container_name: lis_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-lis_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./docker/frontend
    container_name: lis_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./docker/backend
    container_name: lis_backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-lis_db}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
